### ISSUE TITLE
How to unsubscribe from a channel?

### ISSUE THREAD

**Issue by devdotmohit** [ably/ably-js-react-native#14]
While developing an application, I got an email saying that I have crossed the free limit of 100 connections. When got me thinking how to unsubscribe from a channel when unmount is called. Under normal circumstances, componentWillUnmount works well but when fast refresh is enabled, it keeps on opening subscription connections. Let me know if there's a workaround.

**Comment by steelbrain** [comment]
Hi @codeoholic 

Fast refresh is tricky, `componentWillUnmount` should still be triggered tho. Do you have a minimal repro case I can try? As for a workaround, just a normal Reload of the RN app should be good enough

**Comment by devdotmohit** [comment]
Hey @steelbrain! Yes, you are right that `componentWillUnmount` does calls the unsubscribe function, but before it could be called mount is called and a fresh connection is opened.

You can look at the [gist](https://gist.github.com/codeoholic/69b2377aabe5f4751b7a73e36404bf98).

I also spoke with ably support. It was recommended to use dummy data while doing the UI and tests. So, using `isEmulator` and bypassing this problem completely. Connections work fine on real devices.
