### ISSUE TITLE
ES6 imports instead of require

### ISSUE THREAD

**Issue by mk0y** [ably/ably-js-react-native#3]
Hi,

I started using ably on my React Native project and really like it so far. 

There was just small thing that troubled me a little at beginning and that was instead of doing `require('ably').Realtime` I did:

```
import { Realtime } from 'ably'
const realtime = new Realtime('<api key>')
```

Require didn't work on my latest installation of React Native, so maybe you should double check it and improve docs here.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js-react-native/commit/2416653ac682290e59a6ddc6b8be3120611e169b
