### ISSUE TITLE
integrate subscribe into a react component to be added to a state var

### ISSUE THREAD

**Issue by DNWEIJ** [ably/ably-js-react-native#4]
`componentDidMount()` {
  var client = new Realtime({key:"keycode", clientId: "client"});
  var classChannel = client.channels.get('class');
  classChannel .subscribe('all', function(message) {
       this.onReceive(message); 
  });
  onReceive(messages) {
    alert(' never called ...undefied..');
  }

I would not know how to get the received messages into my component. 
since the subscribe doesn't accept a callback (as far as i have tried) what would be the method to get the message to be added to a State varaible this.setState obvious doesn't work...

**Comment by SimonWoolf** [comment]
The above code is subscribing only to messages with message name `'all'`. Is that what you meant to do? If you meant to subscribe to all messages, you do that by using the one-argument form of subscribe(), see https://www.ably.io/documentation/realtime/channels-messages#subscribe
