### ISSUE TITLE
Warning triggered by close()

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-js-react-native#5]
A customer reported an intermittent warning after calling `close()`:

    Ably: WebSocketTransport.onWsClose(): Unclean disconnection of WebSocket

This happens some of the time, but regularly.

**Comment by paddybyers** [comment]
[Internal] See https://app.intercom.io/a/apps/ua39m1ld/respond/inbox/conversation/13982092002 for details

**Comment by SimonWoolf** [comment]
This was determined to be harmless, so fixed by https://github.com/ably/ably-js/commit/8980e0b86
