### ISSUE TITLE
Wont receive messages on android

### ISSUE THREAD

**Issue by stokesbga** [ably/ably-js-react-native#7]
I have the exact same setup between ios and android, and both platforms LOAD ably correctly and even connect to the channel correctly, but my subscribe handler never fires on a message. I tried running on both device and sim, but same situation for both. Any ideas?

**Comment by paddybyers** [comment]
Can you enable verbose logging in the library (set the client option `log: { level: 4}`) and capture that?

Also, is there any indication of an exception in logcat?

**Comment by stokesbga** [comment]
![screen shot 2018-08-02 at 3 24 44 pm](https://user-images.githubusercontent.com/8782370/43606042-40a1d82a-9668-11e8-8b5e-033f380748de.png)


No exception in logcat. Im on RN 53.3. No logs on receive either.. really bizarre.

**Comment by stokesbga** [comment]
The problem was that I use `AblyRealtime.connection.close()` on appstate change to background. I figured it makes sense to prevent reusing the connection if the user closes the app for a long time, but I guess on android, appstate changes all over the place - perhaps because im using react native navigation and technically separate applications are running at once, and switching between them briefly takes the app into background. Very odd, but the solution was just to remove the ably appstate listener.

**Comment by paddybyers** [comment]
I don't know much about react native on Android, but the Android "native" solution to this would be to instance the library from a service context, and then you can be more in control of the lifecycle as various activities come and go.
